import type { Metadata } from "next";
import Link from "next/link";
import { analyticsRetentionDays, sessionTtlHours } from "@drapeproof/product/production/config";

export const metadata: Metadata = {
  title: "Privacy",
  description: "Plain-language details about DrapeProof image processing, anonymous beta usage events, optional feedback, retention, and deletion.",
  alternates: { canonical: "/privacy" },
  openGraph: { url: "/privacy", title: "DrapeProof privacy" },
};

export default function PrivacyPage() {
  const sessionHours = sessionTtlHours(); const analyticsDays = analyticsRetentionDays();
  return <main id="main" className="privacy-page content-wrap">
    <header><p className="product-kicker">PRIVACY</p><h1>Your images deserve plain-language answers.</h1><p>This page describes how the production DrapeProof beta handles an anonymous try-on and limited product-usage data. It does not make promises about systems DrapeProof does not control.</p></header>
    <div className="privacy-grid">
      <section><h2>What is processed and stored</h2><p>DrapeProof processes your source photo and product image to deliver the try-on you request. Private application storage keeps the source, product, immutable AI result, accepted preserved derivative, Passport image, protected-area coordinates, repair attempts, and visual-check results.</p><p>Files are orientation-normalized and rewritten as a canonical JPG or PNG before persistent storage. That removes nonessential source metadata, including GPS EXIF data.</p></section>
      <section><h2>Limited beta usage events</h2><p>DrapeProof stores a small set of first-party product events in its database to understand feature usage, failures, and the aggregate beta funnel. These events may include a workflow step, product category, coarse result state, controlled error code, region count, duration bucket, or Preserve Mode outcome.</p><p>Product analytics never stores image pixels, image or private provider URLs, Blob keys, protected-area coordinates, authentication or ownership tokens, API keys, facial or skin scores, or user-entered protected-area labels.</p></section>
      <section><h2>Optional feedback</h2><p>After a result, you can optionally answer whether DrapeProof was useful and choose a controlled reason. Only “Something else” accepts a short written note, limited to 240 characters. Do not include health or disability information.</p><p>Feedback is used to understand the beta. Submitting it is not consent to train an AI system. Feedback linked to a session is removed when that session is deleted from DrapeProof-controlled storage.</p></section>
      <section><h2>Retention</h2><p>Each product session expires {sessionHours} hours after creation. Expired sessions become inaccessible immediately through request-time checks, and recurring cleanup removes expired database records and DrapeProof-controlled private objects.</p><p>Product events and optional feedback expire after {analyticsDays} days by default. That analytics window is configured separately from product-session retention, and recurring cleanup records only coarse completion counts.</p></section>
      <section><h2>Preserve Mode</h2><p>Preserve Mode is optional and never runs automatically. When you choose “Restore from original,” DrapeProof uses your source photo, the unchanged AI result, protected-area coordinates, pose evidence, and surrounding visual context to decide whether restoration is eligible.</p><p>An accepted restoration creates a separate private derivative and repair trace. It does not overwrite the AI provider result or make another provider generation request.</p></section>
      <section><h2>Third-party AI processing</h2><p>When you choose “Generate my try-on,” your source and product images are sent to Perfect Corp’s YouCam API for the selected virtual try-on. If you opt into the existing face-appearance check, relevant images are also processed by YouCam Skin Analysis.</p><p>Preserve Mode itself does not call YouCam. DrapeProof does not expose provider credentials, private provider task identifiers, or private file links to your browser.</p></section>
      <section><h2>Page and performance telemetry</h2><p>DrapeProof uses Vercel Web Analytics for public page-level traffic and Vercel Speed Insights for performance metrics. Dynamic session, result, and Passport URLs are normalized before page analytics is sent, and URL query strings are removed.</p><p>DrapeProof does not use heatmaps, visual session recording, or video replay of user-uploaded images. Detailed product workflow events remain first-party in DrapeProof’s database.</p></section>
      <section><h2>What deletion does</h2><p>“Delete this session” immediately blocks access and requests deletion of the session’s DrapeProof-controlled images, derivatives, repair artifacts, Passport, verification files, and linked written feedback. Cleanup safely retries storage deletion after a temporary dependency failure.</p><p>DrapeProof cannot claim deletion from Perfect Corp or YouCam systems because the current provider integration has no verified provider-side deletion operation. Provider-controlled copies follow the provider’s own retention practices.</p></section>
      <section><h2>Anonymous browser ownership</h2><p>No account is required. A strong random token is stored in a Secure, HttpOnly, SameSite cookie. DrapeProof stores only a one-way hash with session records. Product analytics does not store the token or create a permanent cross-session user identity; when an aggregation bucket is available, it is one-way and rotates by UTC day.</p></section>
      <section><h2>Technical logs and limits</h2><p>Structured operational logs may retain a request identifier, session identifier, processing phase, category, duration, status, stable error code, and zero-unit preservation counters. Logs redact credentials, cookies, ownership tokens, private storage paths, signed provider URLs, and image bytes.</p><p>DrapeProof does not use these checks for identity verification or medical analysis, and does not claim a physical-fit, accessibility, compatibility, device-function, safety, or external compliance certification.</p></section>
    </div>
    <aside className="privacy-callout"><h2>Want to remove a session?</h2><p>Open the result in this browser and choose “Delete this session.”</p><Link className="primary-button" href="/passports">View your Passports</Link></aside>
  </main>;
}
