import type { PublicTryOnSession } from "@drapeproof/product/live/types";
import { PassportActions } from "./passport-actions";
import { StatusBadge } from "./ui";

export function PassportCard({ session }: { session: PublicTryOnSession }) {
  const result = `/api/sessions/${session.id}/asset/${session.preservedResult ? "preserved" : "result"}?display=1`; const consistent = session.continuity.state === "CONSISTENT";
  const accepted = session.preservationAttempts.filter((attempt) => attempt.state === "RESTORED" || attempt.state === "IMPROVED_BUT_REVIEW");
  return <><article className={`real-passport ${consistent ? "passport-consistent" : "passport-changed"}`}><div className="passport-image"><img src={result} alt={session.preservedResult ? "Your DrapeProof preserved result" : "Your generated try-on result"}/><span>{session.preservedResult ? "DrapeProof · Preserved version · Visual verification only" : "AI provider result · Visual verification only"}</span></div><header><div className="passport-logo"><i>D</i><span><b>DRAPEPROOF</b><small>VISUAL PASSPORT V2</small></span></div><StatusBadge state={consistent ? "success" : "error"}>{consistent ? "Complete" : "Limited"}</StatusBadge></header><div className="passport-meta"><div><span>Date</span><b>{new Date(session.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</b></div><div><span>Category</span><b>{session.category === "CLOTHING" ? "Clothing" : "Bag"}</b></div></div><div className="passport-section"><span>AI generation</span><b>{session.provider.product} · Completed</b></div><div className="passport-section"><span>DrapeProof preservation</span><b>{accepted.length ? `${accepted.length} accepted source restoration${accepted.length === 1 ? "" : "s"} · Version ${session.preservationVersion}` : "No source restoration applied"}</b></div><div className="passport-section"><span>Scene</span><b>{consistent ? "Consistent" : "Changed too much"}</b></div><div className="passport-section passport-area-section"><span>Protected areas</span>{session.continuity.localVerificationEligible ? session.protectedRegionResults.length ? session.protectedRegionResults.map((region) => <div key={region.id}><b>{region.label}</b><StatusBadge state={region.state === "PRESERVED" ? "success" : region.state === "REVIEW" ? "review" : region.state === "CHANGED" ? "error" : "neutral"}>{region.repairState === "RESTORED" ? "Restored" : region.repairState === "IMPROVED_BUT_REVIEW" ? "Improved · Review" : region.state === "PRESERVED" ? "Preserved" : region.state === "REVIEW" ? "Review" : region.state === "CHANGED" ? "Changed" : "Not evaluated"}</StatusBadge></div>) : <b>None selected</b> : <b>Not checked</b>}</div><div className="passport-section"><span>Face appearance</span><b>{session.faceAppearance.state === "CHECKED" ? "Checked" : session.faceAppearance.state === "UNAVAILABLE" ? "Unavailable" : "Not checked"}</b></div><footer><b>Image provenance</b><span>{session.preservedResult ? "Immutable AI result + DrapeProof source-derived repairs" : "AI provider result"}</span><p>DrapeProof checks visual continuity. It does not verify fit, safety, identity, or device compatibility.</p></footer></article><PassportActions id={session.id}/></>;
}
