"use client";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type { PublicTryOnSession, TryOnCategory } from "@drapeproof/product/live/types";
import { ErrorState, FlowTopBar, PrimaryButton, SecondaryButton } from "./ui";
import { fetchSession, patchSession, uploadSessionImage } from "./session-client";

export function ProductStep({ sessionId }: { sessionId: string }) {
  const router = useRouter(); const input = useRef<HTMLInputElement>(null); const [session, setSession] = useState<PublicTryOnSession | null>(null); const [category, setCategory] = useState<TryOnCategory | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (sessionId) fetchSession(sessionId).then((record) => { setSession(record); setCategory(record.category); }).catch((reason) => setError(reason.message)); }, [sessionId]);
  async function choose(value: TryOnCategory) { setCategory(value); setError(""); try { setSession(await patchSession(sessionId, { category: value })); } catch (reason) { setError(reason instanceof Error ? reason.message : "The product type could not be saved."); } }
  async function upload(file: File | undefined) { if (!file || !category) return; setBusy(true); setError(""); try { setSession(await uploadSessionImage(sessionId, "product", file)); } catch (reason) { setError(reason instanceof Error ? reason.message : "The product image could not be added."); } finally { setBusy(false); } }
  if (!sessionId || error && !session) return <main id="main"><ErrorState title="This try-on is unavailable">{error || "Start a new try-on to continue."}<PrimaryButton onClick={() => router.push("/try")}>Start over</PrimaryButton></ErrorState></main>;
  return <main id="main" className="flow-page"><FlowTopBar step="Step 2 of 4" title="Your look" backHref={`/try/photo?session=${encodeURIComponent(sessionId)}`}/><div className="flow-content"><div className="flow-heading"><h1>What do you want to try?</h1><p>Choose a product type, then add a clean image of the item.</p></div><div className="category-grid" role="radiogroup" aria-label="Product type"><button type="button" role="radio" aria-checked={category === "CLOTHING"} onClick={() => choose("CLOTHING")}><span><img src="/product/sample-garment.png" alt="" /></span><b>Clothing</b><small>Shirts, jackets, dresses, and more</small></button><button type="button" role="radio" aria-checked={category === "BAG"} onClick={() => choose("BAG")}><span><img src="/product/sample-bag.png" alt="" /></span><b>Bag</b><small>Handbags and crossbody bags</small></button></div>{category && <section className="product-upload-panel"><div><p className="product-kicker">PRODUCT IMAGE</p><h2>{session?.productImage ? "Product added" : "Add the item"}</h2><p>Use a product-only image with the full item visible and as little background clutter as possible.</p></div>{session?.assetUrls.product && <img src={session.assetUrls.product} alt="Your selected product"/>}<input ref={input} className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" aria-label="Choose product image" onChange={(event) => upload(event.target.files?.[0])}/><SecondaryButton type="button" disabled={busy} onClick={() => input.current?.click()}>{busy ? "Adding item…" : session?.productImage ? "Replace item" : "Choose product image"}</SecondaryButton>{error && <p className="inline-error" role="alert">{error}</p>}{session?.productImage && <PrimaryButton type="button" onClick={() => router.push(`/try/protect?session=${encodeURIComponent(sessionId)}`)}>Choose protected areas</PrimaryButton>}</section>}</div></main>;
}
