"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import type { PublicTryOnSession } from "@drapeproof/product/live/types";
import { ErrorState, FlowTopBar, PrimaryButton, StatusBadge } from "./ui";
import { fetchSession, patchSession } from "./session-client";

export function ReviewStep({ sessionId }: { sessionId: string }) {
  const router = useRouter(); const [session, setSession] = useState<PublicTryOnSession | null>(null); const [face, setFace] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [blocked, setBlocked] = useState<"PAUSED" | "BUDGET" | "">("");
  useEffect(() => { if (sessionId) fetchSession(sessionId).then((record) => { setSession(record); setFace(record.faceAppearance.enabled); }).catch((reason) => setError(reason.message)); }, [sessionId]);
  async function generate() { setBusy(true); setError(""); try { await patchSession(sessionId, { faceAppearanceEnabled: face }); const response = await fetch(`/api/sessions/${encodeURIComponent(sessionId)}?action=generate`, { method: "POST" }); const data = await response.json() as { error?: { code?: string; message?: string; action?: string } }; if (!response.ok) { if (data.error?.code === "GENERATION_PAUSED") setBlocked("PAUSED"); else if (data.error?.code === "DAILY_BUDGET_EXHAUSTED") setBlocked("BUDGET"); throw new Error([data.error?.message, data.error?.action].filter(Boolean).join(" ") || "Your preview could not be started."); } router.push(`/session?id=${encodeURIComponent(sessionId)}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Your preview could not be started."); setBusy(false); } }
  if (!sessionId || error && !session) return <main id="main"><ErrorState title="This try-on is unavailable">{error || "Start a new try-on to continue."}<PrimaryButton onClick={() => router.push("/try")}>Start over</PrimaryButton></ErrorState></main>;
  if (blocked) return <main id="main" className="flow-page"><ErrorState title={blocked === "BUDGET" ? "Try-ons are temporarily full for today." : "New try-ons are temporarily paused."}>{blocked === "BUDGET" ? "We limit daily generations while DrapeProof is in beta. Try again later." : "Your setup is safe. New previews will return when generation resumes."}<Link className="primary-button" href="/">Back to home</Link></ErrorState></main>;
  if (!session?.sourceImage || !session.productImage || !session.category) return <main id="main"><ErrorState title="Your try-on needs a little more">Add both your photo and a product before generating.<PrimaryButton onClick={() => router.push(`/try/photo?session=${encodeURIComponent(sessionId)}`)}>Review setup</PrimaryButton></ErrorState></main>;
  return <main id="main" className="flow-page"><FlowTopBar step="Step 4 of 4" title="Review" backHref={`/try/protect?session=${encodeURIComponent(sessionId)}`}/><div className="flow-content"><div className="flow-heading"><h1>Ready to create your look?</h1><p>Check your photo, product, and protected areas before processing begins.</p></div><div className="review-layout"><section className="review-media"><figure><img src={session.assetUrls.source!} alt="Your try-on photo"/><figcaption>Your photo</figcaption></figure><figure><img src={session.assetUrls.product!} alt="Your selected product"/><figcaption>{session.category === "CLOTHING" ? "Clothing" : "Bag"}</figcaption></figure></section><aside className="review-summary"><div><span>Protected areas</span>{session.protectedRegions.length ? <StatusBadge state="success">{session.protectedRegions.length} selected</StatusBadge> : <StatusBadge state="neutral">None selected</StatusBadge>}</div>{session.protectedRegions.length > 0 && <ul>{session.protectedRegions.map((region, index) => <li key={region.id}><i>{index + 1}</i>{region.label}</li>)}</ul>}<label className="face-option"><input type="checkbox" checked={face} onChange={(event) => setFace(event.target.checked)}/><span><b>Check face appearance</b><small>Optional visual-consistency signals. Not medical or identity analysis.</small></span></label><div className="review-disclosure"><b>Before you continue</b><p>DrapeProof checks visual changes. It does not verify physical fit, product safety, or device compatibility.</p></div>{error && <p className="inline-error" role="alert">{error}</p>}<PrimaryButton type="button" disabled={busy} onClick={generate}>{busy ? "Starting securely…" : "Generate my try-on"}</PrimaryButton></aside></div></div></main>;
}
